name = "Autoencoders"
uuid = "9dc03ea1-ba9b-4764-bb11-8f78b21dd922"
version = "0.0.1"
authors = ["Ciro B Rosa <ciro.rosa@alumni.usp.br>"]

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
TinyMachines = "5d0fdf5f-995e-4f1b-a9e8-363392c4fe32"

[compat]
Flux = "0.16"
TinyMachines = "0.3.6"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
